### ISSUE TITLE
Better configuration naming

### ISSUE THREAD

**Issue by philipnee** [growthbook/growthbook-proxy#11]
Hey Growthbook team, awesome project first of all.

Want to make some suggestions here.
 
Two variable names seem confusing:
`CACHE_STALE_TTL`
`CACHE_EXPIRES_TTL`

In particular, the TTL, as it really means "time to live", which makes the first variable sounds like staled cache expiration time, and cache expiration time for the second var (so TTL is a bit redundant there).  But I think what the first variable means is the time the cache becomes stale and the time the cache gets expired (I assume, evicted?).

Can we rename them to 
`CACHE_EXPIRATION_MS` - Number of Ms before a cache gets expired and therefore becomes stale 
`CACHE_EVICTION_MS` - Number of Ms before a cache is evicted. (Sorry, not 100% sure if CACHE_EXPIRES_TTL actually means the time the cache gets evicted)

**Comment by bryce-fitzsimons** [comment]
Hi Philip! You are correct, these are not the most informative/accurate names. There is a risk of breaking existing configurations though, so as long as we don't get too many other complaints we might keep this one on the back burner.

Hope things are going well at Apache :)
