### ISSUE TITLE
Start with semantic version

### ISSUE THREAD

**Issue by juliojmphjv** [growthbook/growthbook-proxy#29]
## Summary
It would be greatly beneficial if the growthbook proxy was versioned using semantic versioning and had regular releases.

## Expected Behavior
In order to properly run growthbook-proxy in a production setting, I require the ability to pinpoint and utilize a specific version of the associated image.

## Actual Behavior
It seems that the Growthbook proxy has not been versioned or released yet.

**Comment by BadLiveware** [comment]
The current "versioning" also breaks dependency auto update tools like renovate

**Comment by bryce-fitzsimons** [comment]
Good call, implementing better habits now!
