### ISSUE TITLE
Bug 401 Unauthorized in proxy

### ISSUE THREAD

**Issue by tommy04062019** [growthbook/growthbook-proxy#32]
<img width="1410" alt="Screenshot 2023-08-15 at 15 33 16" src="https://github.com/growthbook/growthbook-proxy/assets/8014325/2e54267b-5015-41bb-b3ba-03b3b2f2deb8">
Tested by using docker-compose.proxy.yml. Proxy container is firing above error constantly

**Comment by juliojmphjv** [comment]
Hello @tommy04062019! 
It seems that you have an error related to authentication. When you call growthbook-proxy, are you passing the correct SDK client-key?

**Comment by tommy04062019** [comment]
> Hello @tommy04062019! It seems that you have an error related to authentication. When you call growthbook-proxy, are you passing the correct SDK client-key?

I don't think so

> Hello @tommy04062019! It seems that you have an error related to authentication. When you call growthbook-proxy, are you passing the correct SDK client-key?

**Comment by bryce-fitzsimons** [comment]
I don't immediately know why this is happening for you, but I can say that the error happening when your proxy instance tries to ping the GB API to get a list of SDK Connections. There is an auth issue here. Sometimes this happens if you have special auth headers required on your GB app or if you're using an invalid or self-signed SSL cert.

You could try setting the `NODE_TLS_REJECT_UNAUTHORIZED` env var to `1` to see if this helps.

**Comment by tommy04062019** [comment]
unfortunately, it's not help, I just make a test using `docker-compose.proxy.yml` from the repo of growthbook,:(

**Comment by tommy04062019** [comment]
> I don't immediately know why this is happening for you, but I can say that the error happening when your proxy instance tries to ping the GB API to get a list of SDK Connections. There is an auth issue here. Sometimes this happens if you have special auth headers required on your GB app or if you're using an invalid or self-signed SSL cert.
> 
> You could try setting the `NODE_TLS_REJECT_UNAUTHORIZED` env var to `1` to see if this helps.

Ahh, it's my fault, since I use docker-compose template file for setup proxy, I have to create a new API key before and set to environment variable, need to build docker-compose again to apply. I misunderstood that just configuring the same 2 variables of SECRET_KEY_API is enough
