### ISSUE TITLE
Error trying to connect to Redis in Cluster mode

### ISSUE THREAD

**Issue by rfsbsb** [growthbook/growthbook-proxy#37]
When trying to connect to a redis server in cluster mode, using `CLUSTER_ROOT_NODES=redis://localhost:6379` type of config, I'm getting: 
```
 | 2023-10-27T18:32:18.601Z ioredis:cluster closed because Error: getaddrinfo ENOTFOUND redis://localhost
 |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
 |   errno: -3008,
 |   code: 'ENOTFOUND',
 |   syscall: 'getaddrinfo',
 |   hostname: 'redis://localhost'
 | }
```

I've identified the problem being on `RedisCache.transformRootNodes` function where it appends back the protocol to the URL. If I modify that function to remove it, it works fine.

The example above is using localhost, but I'm having the exact same issue with AWS elasticache.

According to `ioredis` documentation we should specify only host and port, not protocol, but right now I cannot specify only host on the env var, otherwise it malforms it when it prepend the protocol.

I see no issue using `CACHE_CONNECTION_URL=redis://localhost:6379` with `USE_CLUSTER=false` however. This might be due to the way

**Comment by bryce-fitzsimons** [comment]
This one must have slipped by since I think most folks have been using `CLUSTER_ROOT_NODES_JSON` instead of `CLUSTER_ROOT_NODES`. So to be clear, you're basically suggesting making this change?

before:
```
const host = url.protocol + "//" + url.hostname + url.pathname;
```
after:
```
const host = url.hostname + url.pathname;
```

**Comment by rfsbsb** [comment]
Hey, thanks for coming back to me. 

Yeah I haven't tried with `CLUSTER_ROOT_NODES_JSON` but I since the current implementation for `CLUSTER_ROOT_NODES` is not working properly I think this needs to be fixed or this option should be removed.

If you wish I can create a PR for it.

**Comment by rfsbsb** [comment]
Sorry, I went ahead and created a PR https://github.com/growthbook/growthbook-proxy/pull/38

**Comment by bryce-fitzsimons** [comment]
Thank you for the PR. I've been looking into this a bit and it seems like using the standard Node URL parser for redis:// root nodes can lead to far too many edge cases. For example, `new URL("redis://:password@192.168.0.1:1234")` leads to a hostname of `""`, pathname of `"//:password@192.168.0.1:1234"`, and port of `""`.

I believe it would be better to only support CLUSTER_ROOT_NODES_JSON and to deprecate CLUSTER_ROOT_NODES entirely. Please let me know if any concerns, and thanks again.

**Comment by rfsbsb** [comment]
Yeah, I agree. It looks like `CLUSTER_ROOT_NODES_JSON` is enough and `CLUSTER_ROOT_NODES` creates only confusion.
