### ISSUE TITLE
Missing `@growthbook/growthbook` package in `growthbook/proxy:git-e724f6d`

### ISSUE THREAD

**Issue by minuchi** [growthbook/growthbook-proxy#64]
## Environments

* Docker image: `growthbook/proxy:git-e724f6d`

## Description

The `growthbook/proxy:git-e724f6d` image fails to start within a Docker container due to a missing dependency: the `@growthbook/growthbook` package. This results in the error message shown in the attached image.

**Reproduction Steps:**

1. Run the following command:

```bash
docker run -d -p 3300:3300 \
  -e "GROWTHBOOK_API_HOST=https://growthbook-api.example.com" \
  -e "SECRET_API_KEY=key_abc123" \
  --name gbproxy growthbook/proxy:git-e724f6d
```

2. Observe the container logs for the error message related to the missing package.
![image](https://github.com/growthbook/growthbook-proxy/assets/112928337/554ece93-6267-4106-a802-211f5057bbb8)

**Comment by bryce-fitzsimons** [comment]
Very sorry about this! Just patched the issue in v1.1.7. Please let me know if you're still running into issues.

Closing the issue for now; feel free to re-open.
