### ISSUE TITLE
Stream shows empty

### ISSUE THREAD

**Issue by RarDFS** [growthbook/growthbook-proxy#69]
### Summary

Right now i am receiving the empty ping from the stream proxy and no feature flags

#### Expected Behavior

To get the feature flags

#### Current Behavior

When doing `curl -N https://.../sub/sdk-` this is the only response that i get

```
retry: 10000

data: 

data: 
```

**Comment by bryce-fitzsimons** [comment]
Hello. Are you updating any feature flags in the GB app while curl is running? Does the standard features endpoint on your proxy return your full SDK payload?

**Comment by RarDFS** [comment]
@bryce-fitzsimons i fixed it, it was a issue of not knowing how the stream works 😓
