### ISSUE TITLE
Docker image crash issue

### ISSUE THREAD

**Issue by thearchitectxy** [growthbook/growthbook-proxy#7]
<img width="798" alt="Screenshot 2023-02-02 at 7 44 44 PM" src="https://user-images.githubusercontent.com/84636940/216420642-13fb8ee8-164c-4e77-9690-4a05cb602394.png">
Hi i am using the latest docker image in my kubernetes deployment but i am having this issue, any way of resolving? thanks

**Comment by thearchitectxy** [comment]
@jdorn  @bryce-fitzsimons  your help needed

**Comment by bryce-fitzsimons** [comment]
Hi @thearchitectxy , the issue should be resolved now (we had an error on the `start` script in the latest release!). Please let me know if this resolves your issue.

**Comment by thearchitectxy** [comment]
> Hi @thearchitectxy , the issue should be resolved now (we had an error on the `start` script in the latest release!). Please let me know if this resolves your issue.

yes pod restarted and new mage works fine now thanks
